---
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: caas-default
spec:
  privileged: false
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  hostIPC: false
  hostNetwork: false
  hostPID: false
  volumes:
    - 'configMap'
    - 'downwardAPI'
    - 'emptyDir'
    - 'persistentVolumeClaim'
    - 'projected'
    - 'secret'
    - 'hostPath'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:default-psp
rules:
- apiGroups:     ['extensions']
  resources:     ['podsecuritypolicies']
  verbs:         ['use']
  resourceNames: ['caas-default']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:default-psp
roleRef:
  kind: ClusterRole
  name: caas:default-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize system:nodes group to be able to create mirror pods
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:nodes
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
