apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhookcfg-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:webhookcfg-controller
  namespace: kube-system
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:webhookcfg-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:webhookcfg-controller
subjects:
- kind: ServiceAccount
  name: webhookcfg-controller
  namespace: kube-system